"""Add GeneticAlterations model

Revision ID: 2e5cbf08f798
Revises: 7482d1f94dce
Create Date: 2025-06-26 01:56:47.896118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5cbf08f798'
down_revision = '7482d1f94dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genetic_alterations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('EGFR_cna', sa.Integer(), nullable=True),
    sa.Column('ALK_cna', sa.Integer(), nullable=True),
    sa.Column('ROS1_cna', sa.Integer(), nullable=True),
    sa.Column('BRAF_cna', sa.Integer(), nullable=True),
    sa.Column('MET_cna', sa.Integer(), nullable=True),
    sa.Column('RET_cna', sa.Integer(), nullable=True),
    sa.Column('ERBB2_cna', sa.Integer(), nullable=True),
    sa.Column('KRAS_cna', sa.Integer(), nullable=True),
    sa.Column('TP53_cna', sa.Integer(), nullable=True),
    sa.Column('STK11_cna', sa.Integer(), nullable=True),
    sa.Column('KEAP1_cna', sa.Integer(), nullable=True),
    sa.Column('PIK3CA_cna', sa.Integer(), nullable=True),
    sa.Column('NRAS_cna', sa.Integer(), nullable=True),
    sa.Column('NTRK1_cna', sa.Integer(), nullable=True),
    sa.Column('NTRK2_cna', sa.Integer(), nullable=True),
    sa.Column('NTRK3_cna', sa.Integer(), nullable=True),
    sa.Column('CD274_cna', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genetic_alterations')
    # ### end Alembic commands ###
