"""Add link column to notifications

Revision ID: 327e249e9950
Revises: 8ae49f3fc0a2
Create Date: 2025-07-13 03:09:41.259690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '327e249e9950'
down_revision = '8ae49f3fc0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('link', sa.String(length=255), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'link')

    # ### end Alembic commands ###
