"""Add AncestryScores model

Revision ID: 4c585a4dbe10
Revises: fdbc3289eeef
Create Date: 2025-06-26 02:16:38.603966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c585a4dbe10'
down_revision = 'fdbc3289eeef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ancestry_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('EUR', sa.Float(), nullable=True),
    sa.Column('AFR', sa.Float(), nullable=True),
    sa.Column('EAS', sa.Float(), nullable=True),
    sa.Column('AMR', sa.Float(), nullable=True),
    sa.Column('SAS', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ancestry_scores')
    # ### end Alembic commands ###
