"""Add diagnosed column to ClinicalData

Revision ID: 66dd5886b9df
Revises: b09c86d0a000
Create Date: 2025-05-28 05:07:35.400938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dd5886b9df'
down_revision = 'b09c86d0a000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_data', schema=None) as batch_op:
        batch_op.drop_column('diagnosed')

    # ### end Alembic commands ###
