"""Add radiation_therapy to ClinicalData

Revision ID: 7482d1f94dce
Revises: c068ae32edf3
Create Date: 2025-06-26 01:42:57.206400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7482d1f94dce'
down_revision = 'c068ae32edf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radiation_therapy', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_data', schema=None) as batch_op:
        batch_op.drop_column('radiation_therapy')

    # ### end Alembic commands ###
