"""Add type to Notification

Revision ID: 7b792730b5bb
Revises: 327e249e9950
Create Date: 2025-07-13 23:12:51.523776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b792730b5bb'
down_revision = '327e249e9950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

  

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
