"""fix ct_scan_image type

Revision ID: b6f21cdd2560
Revises: 66dd5886b9df
Create Date: 2025-06-05 14:38:48.790524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f21cdd2560'
down_revision = '66dd5886b9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imaging_data', schema=None) as batch_op:
        batch_op.alter_column('ct_scan_image',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imaging_data', schema=None) as batch_op:
        batch_op.alter_column('ct_scan_image',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
