"""Add clinical, imaging, treatment tables

Revision ID: e5621892d22c
Revises: de9105c1c333
Create Date: 2025-05-26 02:41:14.264390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5621892d22c'
down_revision = 'de9105c1c333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('de_stag', sa.String(length=10), nullable=True),
    sa.Column('de_stag_7thed', sa.String(length=10), nullable=True),
    sa.Column('histology_cat', sa.String(length=50), nullable=True),
    sa.Column('lesionsize', sa.Float(), nullable=True),
    sa.Column('treatlc', sa.String(length=50), nullable=True),
    sa.Column('lung_cancer', sa.String(length=10), nullable=True),
    sa.Column('diagadas', sa.Boolean(), nullable=True),
    sa.Column('diagasbe', sa.Boolean(), nullable=True),
    sa.Column('diagbron', sa.Boolean(), nullable=True),
    sa.Column('diagchas', sa.Boolean(), nullable=True),
    sa.Column('diagchro', sa.Boolean(), nullable=True),
    sa.Column('diagcopd', sa.Boolean(), nullable=True),
    sa.Column('diagdiab', sa.Boolean(), nullable=True),
    sa.Column('diagemph', sa.Boolean(), nullable=True),
    sa.Column('diagfibr', sa.Boolean(), nullable=True),
    sa.Column('diaghear', sa.Boolean(), nullable=True),
    sa.Column('diaghype', sa.Boolean(), nullable=True),
    sa.Column('diagpneu', sa.Boolean(), nullable=True),
    sa.Column('diagsarc', sa.Boolean(), nullable=True),
    sa.Column('diagsili', sa.Boolean(), nullable=True),
    sa.Column('diagstro', sa.Boolean(), nullable=True),
    sa.Column('diagtube', sa.Boolean(), nullable=True),
    sa.Column('canclung', sa.Boolean(), nullable=True),
    sa.Column('cigsmok', sa.Boolean(), nullable=True),
    sa.Column('age_quit', sa.Integer(), nullable=True),
    sa.Column('pkyr', sa.Float(), nullable=True),
    sa.Column('smokeday', sa.Float(), nullable=True),
    sa.Column('smokeyr', sa.Integer(), nullable=True),
    sa.Column('progressed_ever', sa.Boolean(), nullable=True),
    sa.Column('prog_days_1st', sa.Integer(), nullable=True),
    sa.Column('canc_free_days', sa.Integer(), nullable=True),
    sa.Column('candx_days', sa.Integer(), nullable=True),
    sa.Column('scr_res0', sa.String(length=20), nullable=True),
    sa.Column('scr_res1', sa.String(length=20), nullable=True),
    sa.Column('scr_res2', sa.String(length=20), nullable=True),
    sa.Column('biop0', sa.Boolean(), nullable=True),
    sa.Column('biop1', sa.Boolean(), nullable=True),
    sa.Column('biop2', sa.Boolean(), nullable=True),
    sa.Column('invas0', sa.Boolean(), nullable=True),
    sa.Column('invas1', sa.Boolean(), nullable=True),
    sa.Column('invas2', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('imaging_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ct_scan_image', sa.LargeBinary(), nullable=True),
    sa.Column('scan_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('treatment_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_post_surg', sa.Integer(), nullable=True),
    sa.Column('rad_stop_days', sa.Integer(), nullable=True),
    sa.Column('treat_days', sa.Integer(), nullable=True),
    sa.Column('treat_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment_data')
    op.drop_table('imaging_data')
    op.drop_table('clinical_data')
    # ### end Alembic commands ###
