"""Add HypoxiaScores model

Revision ID: fdbc3289eeef
Revises: 2e5cbf08f798
Create Date: 2025-06-26 02:14:11.161971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbc3289eeef'
down_revision = '2e5cbf08f798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypoxia_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('RAGNUM_HYPOXIA_SCORE', sa.Float(), nullable=True),
    sa.Column('BUFFA_HYPOXIA_SCORE', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hypoxia_scores')
    # ### end Alembic commands ###
